[package]
name = "Ass2"
version = "0.1.0"
authors = ["SarmadKhoja95 <sarmadkhoja.sk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
